apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # these are replica set lables.
  labels:
    purpose : dp-demo
    project : roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      purpose: dp-demo
      project: roboshop
  #pod definition.
  template:
    metadata:
      labels:
        purpose: dp-demo
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx:latest