apiVersion: apps/v1
kind: Deployment
metadata:
  name: taints-tolerations
  # these are replica set lables.
  labels:
    purpose : tolerations-demo
    project : roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      purpose: tolerations-demo
      project: roboshop
  #pod definition.
  template:
    metadata:
      labels:
        purpose: tolerations-demo
        project: roboshop
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-192-168-30-245.ec2.internal  #from labels (k9s describe)
      containers:
      - name: nginx
        image: nginx:latest
      tolerations:
      - key: "project"
        operator: "Equal"
        value: "roboshop"
        effects: "NoSchedule"