apiVersion: v1
kind: pod
metadata: 
  name: nginx
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values: 
                - us-east-1b
          - matchExpressions:
              - key: disktype
                operator: In
                values: 
                - ssd      
  containers: 
  - name: nginx
    image: nginx
    imagePullPoliciy: Always