
apiVersion: v1
kind: pod
metadata: 
  name: pod-3
spec: 
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        # pod labels
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values: 
            - pod-1
            - pod-2
        topologyKey: topology:kubernetes.io/zone           
  containers:   
  - name: nginx
    image: nginx
    imagePullPoliciy: Always